basePath: '{{.BasePath}}'
definitions:
  objects.Response:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /v1/elastic/detail:
    get:
      consumes:
      - application/json
      description: Show data by id from some index
      parameters:
      - description: uuid
        in: query
        name: uuid
        type: string
      - description: index
        in: query
        name: index
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/objects.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get data by id
      tags:
      - Elastic
  /v1/elastic/field/detail:
    get:
      consumes:
      - application/json
      description: Show data by field from some index with value
      parameters:
      - description: field
        in: query
        name: field
        type: string
      - description: value
        in: query
        name: value
        type: string
      - description: index
        in: query
        name: index
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/objects.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get data by field
      tags:
      - Elastic
  /v1/elastic/version:
    get:
      consumes:
      - application/json
      description: Show Elasticsearch version from url
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/objects.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Elasticsearch version
      tags:
      - Elastic
swagger: "2.0"
